- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 36000 # 10h # Sunrise-RoleTime
  - !type:DepartmentTimeRequirement
    department: Security
    time: 7200 # 2h # Sunrise-RoleTime

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 36000 # 10h # Sunrise-RoleTime
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 18000 # 5h # Sunrise-RoleTime
  - !type:DepartmentTimeRequirement
    department: Security
    time: 18000 # 5h # Sunrise-RoleTime

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 36000 # 10h # Sunrise-RoleTime
  - !type:DepartmentTimeRequirement
    department: Security
    time: 18000 # 5h # Sunrise-RoleTime
  # should be changed to nukie playtime when thats tracked (wyci)
